### ISSUE TITLE
post https://domain-name/api/nexopos/v4/setup/database 404 not found

### ISSUE THREAD

**Issue by MohamedHassan-dev** [Blair2004/NexoPOS#1476]
hi i am try install nexo v4.8.17 at bluehost and when i am try to setup database return this error 

`post https://domain-name/api/nexopos/v4/setup/database 404 not found`

i am install project inside folder inside public_html and composer install and storage link and app key all commend rurn without any issue but when i am try to setup project from url https://domain-name/subfolder/public/do-setup#/database 

return error any help please

**Comment by Blair2004** [comment]
Hi, 
Thank you for your first issue. As it's the first time you're posting, we would like to let you know the issue is not in valid for. Read this #501 to understand how to create an issue (for subsequent requests).

You cannot access your website from that URL. The "public" folder should not be visible on the URL. This will expose your .env and your installation will be hacked. Make sure to set the document_root where the .env file is located.

Kind regards.

**Comment by Blair2004** [comment]
How it this going so far ?

**Comment by Blair2004** [comment]
Closed for inactivity.
