### ISSUE TITLE
Sign In Page CSS Issue after enabling PIN Login Module

### ISSUE THREAD

**Issue by gurulancer** [Blair2004/NexoPOS#1480]
After PIN IN Modules enabled, The sign in page looks strange and broken like attach file

https://u.pcloud.link/publink/show?code=XZ2PUtVZSoRu8zDRCa5F85WrkHs60XAezc5V

How to fix this ?

<img width="1201" alt="Sign In CSS Issue" src="https://github.com/Blair2004/NexoPOS/assets/132946315/6f6dd37b-d9b8-4305-b5ab-1c8778b1cdda">

**Comment by Blair2004** [comment]
Usually, this is caused by the symlink not created after installing a module or by a wrong file permissions. This is fixed like this:

*Fixing Symlinking*
`php artisan modules:symlink [namespace]`

Replace [namespace] with the actual module namespace. This can be found on the config.xml file at the root of every module.

*Fixing Permissions*
`find -type d -exec chmod 755 {} \;`
`find -type f -exec chmod 644 {} \;`

This will change chmod for files and directories.

Let us know if that helps.

**Comment by gurulancer** [comment]
Thanks a lot
