### ISSUE TITLE
[Issue] Units of measure not working as expected

### ISSUE THREAD

**Issue by josephelkhoury** [Blair2004/NexoPOS#1494]
**Describe the bug**
Units of measure are not working as expected or am I doing something wrong?

**To Reproduce**
If I add a new unit group for Wine bottles and then I create 2 units: Bottle, Glass.
Glass being the base unit with a value of 1, and Bottle with a value of 8 (8 glasses make 1 bottle).

If I do a procurement of 1 bottle and try to sell 1 glass, it says that the stock is 0.

**Expected behavior**
Shouldn't the system calculate that 1 bottle = 8 glasses automatically?
Isn't it how the units groups and units work?

**Environment:**
 - NexoPOS 4.8.18

**Comment by Blair2004** [comment]
Hi, 
It's not an error, but a feature that we haven't yet added. In fact, we should add a feature that converts units. For example, in your case, if you purchase a bottle, you'll have the option to convert the bottle into glasses so that it can be sold directly. We we'll DEFINITELY add this feature. But only on v5.

Meanwhile? It would help if you made a procurement using the glasses unit.

Hope this helps.
